name: notion-backup-docker-run

on:
  # adds a "run workflow" button to the page
  workflow_dispatch:

# See https://github.com/marketplace/actions/docker-run-step
# See https://github.com/addnab/docker-run-action

jobs:
  run-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: kohlerdominik/docker-run-action@v1
        with:
          # public, private or local image
          image: jckleiner/notion-backup
          # pass or create environment variables
          environment: |
            NOTION_SPACE_ID=${{ secrets.NOTION_SPACE_ID }}
            NOTION_EMAIL=${{ secrets.NOTION_EMAIL }}
            NOTION_PASSWORD=${{ secrets.NOTION_PASSWORD }}
            
            GOOGLE_DRIVE_ROOT_FOLDER_ID=${{ secrets.GOOGLE_DRIVE_ROOT_FOLDER_ID }}
            GOOGLE_DRIVE_SERVICE_ACCOUNT=${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT }}
            GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON=${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_JSON }}
            GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH=${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_SECRET_FILE_PATH }}
            
            DROPBOX_ACCESS_TOKEN=${{ secrets.DROPBOX_ACCESS_TOKEN }}
            DROPBOX_APP_KEY=${{ secrets.DROPBOX_APP_KEY }}
            DROPBOX_APP_SECRET=${{ secrets.DROPBOX_APP_SECRET }}
            DROPBOX_REFRESH_TOKEN=${{ secrets.DROPBOX_REFRESH_TOKEN }}
            
            NEXTCLOUD_EMAIL=${{ secrets.NEXTCLOUD_EMAIL }}
            NEXTCLOUD_PASSWORD=${{ secrets.NEXTCLOUD_PASSWORD }}
            NEXTCLOUD_WEBDAV_URL=${{ secrets.NEXTCLOUD_WEBDAV_URL }}

          # run is required: "Error: Input required and not supplied: run"
          run: |
            echo "hello world"
            uname -a



